org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.249
loader_version_range=[4,)

mod_id=adventureworldgen
mod_name=AdventureWorldGen
mod_version=0.1.0
mod_group_id=io.github.luoyan.adventureworldgen
mod_license=All Rights Reserved
mod_authors=\u7f57\u8a00
mod_description=AdventureWorldGen for Minecraft 1.21.1.
